name: VATSIM TR Sector Notifier

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Önceki state'i indir
        uses: actions/download-artifact@v4
        with:
          name: vatsim-state
        continue-on-error: true

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Gereksinimleri kur
        run: pip install -r requirements.txt

      - name: Scripti çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: State'i kaydet
        uses: actions/upload-artifact@v4
        with:
          name: vatsim-state
          path: last_state.txt