name: VATSIM TR Sector Notifier

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Gereksinimleri kur
        run: pip install -r requirements.txt

      - name: State cache restore
        uses: actions/cache/restore@v4
        with:
          path: last_state.txt
          key: vatsim-sector-state

      - name: Scripti çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: State cache save
        uses: actions/cache/save@v4
        with:
          path: last_state.txt
          key: vatsim-sector-state